name: bugfix-feature

on:
  push:
    branches: [ bugfix, feature ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # for notification to microsoft Teams
    - name: BeverOps Build Notification
      uses: toko-bifrost/ms-teams-deploy-card@3.1.2
      with:
        webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}
        github-token: ${{ github.token }}
        environment: None
        timezone: "Asia/Kolkata"
        card-layout-start: compact
        card-layout-exit: complete
        show-on-start: true
        show-on-exit: true
        custom-facts: |
          - name: Repository
            value: ${{github.repository}}
          - name: ImageTag
            value: ${{ github.sha }}
        enable-view-status-action: true
        enable-review-diffs-action: true
        view-status-action-text: "View Status"

    #checkout actions
    - uses: actions/checkout@v2

    # Since the project is python based project commented the mavenbased steps
    # javasetup for maven goals
    # - name: Set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    #
    # # maven goals
    # - name: Build with Maven
    #   run: mvn clean install -DskipTests=true
    #
    # # buildx
    # - name: Docker Buildx
    #   uses: crazy-max/ghaction-docker-buildx@v3.3.0
    #   with:
    #     buildx-version: latest # optional, default is latest
    #     qemu-version: latest # optional, default is latest
